config/routes.rb
Rails.application.routes.draw do

  resources :igcls do
    collection do
      post :confirm
    end
  end

  resources :users do
    collection do
      post :favorite
    end
  end

  resources :favorites do
    collection do
      post :favorite
    end
  end

  resources :users, only: [:new,:create,:show]
  resources :sessions, only: [:new,:create,:destroy]
  resources :favorites, only: [:create, :destroy]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :igcl
end

app/models/igcl.rb
class Igcl < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true,length: { in: 1..140 }
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  mount_uploader :image, ImageUploader

end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :igcl, dependent: :destroy
  has_many :favorites,dependent: :destroy
  has_many :favorite_igcls, through: :favorites,source: :igcl

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(igcl_id: params[:igcl_id])
    redirect_to igcls_url, notice: "#{favorite.igcl.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to igcls_url, notice: "#{favorite.igcl.user.name}さんのブログをお気に入り解除しました"
  end

  def index
    @favorites = current_user.favorite_igcls
  end
end

app/controllers/igcls_controller.rb
class IgclsController < ApplicationController
  before_action :check_login
  before_action :set_igcl,only: [:show, :edit, :update, :destroy]
  before_action :ensure_correct_user,only: [:edit, :update, :destroy]
  def index
    @igcls=Igcl.all
  end

  def create
    @igcl=Igcl.new(igcl_params)
    @igcl.image.retrieve_from_cache! params[:cache][:image] if params[:cache][:image].present?
    @igcl.user_id = current_user.id
    if @igcl.save
      ContactMailer.contact_mail(@igcl).deliver
      redirect_to igcls_path, notice: "投稿を作成しました！"
    else
      render 'new'
    end
  end

  def new
    if params[:back]
      @igcl = Igcl.new(igcl_params)
      @igcl.image.retrieve_from_cache! params[:cache][:image]
    else
      @igcl=Igcl.new
    end
  end

  def show
    @igcl = Igcl.find(params[:id])
    @user = @igcl.user
    @favorite = current_user.favorites.find_by(igcl_id: @igcl.id)
  end

  def edit

  end

  def update
    if @igcl.update(igcl_params)
      redirect_to igcls_path, notice: "投稿を編集しました！"
    else
      render 'edit'
    end
  end

  def destroy
    @igcl.destroy
    redirect_to igcls_path, notice:"投稿を削除しました！"
  end

  def confirm
    @igcl = Igcl.new(igcl_params)
    @igcl.user_id = current_user.id
    render :new if @igcl.invalid?

  end

  private

  def igcl_params
    params.require(:igcl).permit(:title,:content,:image,:image_cache)
  end

  def set_igcl
    @igcl=Igcl.find(params[:id])
  end

  def check_login
    if !logged_in?
      redirect_to new_session_path
    end
  end

  def ensure_correct_user
    @igcl = Igcl.find_by(id:params[:id])
    if @igcl.user_id != @current_user.id
      flash[:notice] = "権限がありません"
      redirect_to(igcls_path)
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @favorites_igcls = @user.favorite_igcls
  end

  def favorite

  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/igcls_helper.rb
module IgclsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_igcls_path
    elsif action_name == 'edit'
      igcl_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/index.html.erb
<h2>お気に入り一覧</h2>
<% @favorites.each do |favorite_igcl| %>
  <table>
    <tr>
      <th>画像</th>
      <td><%= image_tag favorite_igcl.image %></td>
    </tr>
    <tr>
      <th>タイトル</th>
      <td><%= favorite_igcl.title %></td>
    </tr>
    <tr>
      <th>内容</th>
      <td><%= favorite_igcl.content %></td>
    </tr>
    <tr>
      <th>投稿者</th>
      <td><%= favorite_igcl.user.name%></td>
    </tr>
  </table>
  <br>
<% end %>

<%= link_to "ユーザーページへ戻る", user_path(current_user.id), class: "actions" %>

app/views/igcls/_form.html.erb
<div class = forms>
<%= form_with(model: @igcl, local: true ,url: choose_new_or_edit) do |form| %>
  <% if @igcl.errors.any? %>
    <div id="error_explanation">
      <h2><%= @igcl.errors.count %>件のエラーがあります。</h2>
      <ul>
        <% @igcl.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :title %>
    <br>
    <%= form.text_field :title %>
  </div>
  <div class="field">
    <%= form.label :content %>
    <br>
    <%= form.text_field :content %>
  </div>
  <div class="field">
    <%= form.label :image -%>
    <%= image_tag(@igcl.image.url) if @igcl.image.url -%>
    <%= form.file_field :image, class: "igcl_image" %>
    <%= form.hidden_field :image_cache %>
  </div>

  <%= form.submit "投稿する", class: "btn btn-warning actions" %>


<% end %>
</div>

<%= link_to "投稿一覧画面にもどる", igcls_path, class: "btn btn-default actions"  %>

app/views/igcls/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @igcl, url: igcls_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>


  <p>タイトル:<%= @igcl.title %></p>
  <p>本文:<%= @igcl.content %></p>
  <p>画像<%= image_tag @igcl.image %></p>
  <%= hidden_field_tag :"cache[image]",@igcl.image.cache_name %>
  <%= form.submit  " 投稿する", class: 'btn btn-warning actions'%>
<% end %>

<%= form_with(model: @igcl, url: new_igcl_path, local: true, method: 'get') do |form| %>
  <%= hidden_field_tag :"cache[image]",@igcl.image.cache_name %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.submit "もどる", name: 'back' , class: 'btn btn-default actions'%>
<% end %>

app/views/igcls/edit.html.erb
<h2>投稿を編集する</h2>

<%= render 'form' %>

app/views/igcls/index.html.erb
<h1>投稿一覧</h1>
<br>
<table>
  <tr>
    <th>タイトル</th>
    <th>内容</th>
    <th>投稿者</th>
  </tr>

<% @igcls.each do |igcl| %>
  <tr>
    <td><%= igcl.title %></td>
    <td><%= igcl.content %></td>
    <td><%= igcl.user.name %></td>

    <td><button type="button" class="btn btn-info btn-sm"><%= link_to "詳細", igcl_path(igcl.id) %></button>
    <% if current_user.id == igcl.user_id %>
      <button type="button" class="btn btn-warning btn-sm"><%= link_to "編集", edit_igcl_path(igcl.id) , data: { confirm: "本当に編集していいですか？" } %></button>
      <button type="button" class="btn btn-danger btn-sm"><%= link_to "削除", igcl_path(igcl.id), method: :delete ,data: { confirm: "本当に削除していいですか？" } %></button></td>
    <% end %>
  </tr>

<% end %>
</table>
<br>

<%= link_to "新規投稿", new_igcl_path, class: "btn btn-default actions" %>

app/views/igcls/new.html.erb
<h2> 投稿を作成する</h2>

<%= render 'form' %>

app/views/igcls/show.html.erb
<h1>投稿詳細画面</h1>
<p>タイトル: <%= @igcl.title %></p>
<p>内容: <%= @igcl.content %></p>
<p>画像: <%= image_tag @igcl.image %></p>

<%= link_to 'Edit', edit_igcl_path(@igcl) , class: 'btn btn-primary'%> |
<%= link_to 'Back', igcls_path %>
<br>
<br>
<% unless @igcl.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(igcl_id: @igcl.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>
<br>
<br>
<%= link_to ' 投稿一覧へ', igcls_path , class: 'btn btn-info'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sns1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width">
  </head>

  <header>
    <nav class="navbar navbar-default navbar-custom">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
            <span class="sr-only">Bootstrap</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div id="gnavi" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="/igcls">index</a></li>
            <li><a href="/igcls/new">new</a></li>
            <% if logged_in? %>
              <li><%= link_to "Profile", user_path(current_user.id) %></li>
              <li><%= link_to "Logout", session_path(current_user.id), method: :delete %></li>
            <% else %>
              <li><%= link_to "Sign up", new_user_path %></li>
              <li><%= link_to "Login", new_session_path %></li>
            <% end %>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </header>



  <body>
    <% flash.each do |key, value| %>
    <div class="alert alert-success">
      <%= content_tag(:div, value, class: "#{key}") %>
    </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/users/favorite.html.erb
<p>お気に入り一覧</p>

app/views/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>  
  <%= f.label :"名前" %>
  <%= f.text_field :name %>
<br>
  <%= f.label :"メールアドレス" %>
  <%= f.email_field :email %>
<br>
  <%= f.label :"パスワード" %>
  <%= f.password_field :password %>
<br>
  <%= f.label :"確認用パスワード" %>
  <%= f.password_field :password_confirmation %>
<br>
  <%= f.submit " 新規登録をする" , :class => 'btn btn-default'%>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス: <%= @user.email %></p>

<br>

<p><%= link_to '投稿一覧へ', igcls_path, class: 'actions' %></p>
<br>
<p><%= link_to ' お気に入り一覧へ', favorites_path, class: 'actions' %></p>